apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: sls-dev
    devEnvApprovers:
    - todo
    dockerRegistryOrg: oci
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "496297688115"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: de-gcp-sls-dev
    provider: gke
    registry: europe-west3-docker.pkg.dev/de-gcp-sls-dev
    zone: europe-west3-a
  environments:
  - key: dev
    owner: raviyadav57
    repository: Jenkins-X-walk-through
  - key: staging
  - key: production
  ingress:
    domain: 34.141.18.239.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  pipelineUser:
    username: ravi.yadav2@soprasteria.com
  repository: nexus
  secretStorage: gsm
  vault: {}
  webhook: lighthouse
